### ISSUE TITLE
Unittests segv with ldc 1.12

### ISSUE THREAD

**Issue by pjotrp** [biod/BioD#44]
Using the meson branch build I get with ldc 1.12 - but not with ldc 1.0.7:

```
Thread 1 "biod_test" received signal SIGSEGV, Segmentation fault.
0x0000000000595eba in _D3std11parallelism8TaskPool16tryDeleteExecuteMFPSQBwQBv12AbstractTaskZv ()
(gdb) bt
#0  0x0000000000595eba in _D3std11parallelism8TaskPool16tryDeleteExecuteMFPSQBwQBv12AbstractTaskZv ()
#1  0x000000000050ab05 in _D3std11parallelism__T4TaskS_D3bio4core4bgzf5block19decompressBgzfBlockFSQBrQBqQBoQBm9BgzfBlockCQCoQCn5utils7memoize__T5CacheTQCcTSQDxQDwQDuQDs21DecompressedBgzfBlockZQBwZQBpTQDzTQDgZQGf10yieldForceMFNcNdNjNeZQDb (this=...)
    at /gnu/store/4yxy8m5x3fqj5brmdd1c0chqz1h9q6qz-ldc-1.12.0/include/d/std/parallelism.d:608
#2  0x0000000000483ccb in _D3std11parallelism__T4TaskS_D3bio4core4bgzf5block19decompressBgzfBlockFSQBrQBqQBoQBm9BgzfBlockCQCoQCn5utils7memoize__T5CacheTQCcTSQDxQDwQDuQDs21DecompressedBgzfBlockZQBwZQBpTQDzTQDgZQGf6__dtorMFNfZv (this=...)
    at /gnu/store/4yxy8m5x3fqj5brmdd1c0chqz1h9q6qz-ldc-1.12.0/include/d/std/parallelism.d:750
#3  0x00000000005b477b in rt_finalizeFromGC ()
#4  0x00000000005c8465 in _D2gc4impl12conservativeQw3Gcx5sweepMFNbZm ()
#5  0x00000000005c60f2 in _D2gc4impl12conservativeQw3Gcx11fullcollectMFNbbZm ()
#6  0x00000000005c6327 in _D2gc4impl12conservativeQw14ConservativeGC__T9runLockedS_DQCeQCeQCcQCnQBs18fullCollectNoStackMFNbZ2goFNbPSQEaQEaQDyQEj3GcxZmTQvZQDfMFNbKQBgZm ()
#7  0x00000000005ac25d in gc_term ()
#8  0x00000000005b168b in rt_term ()
#9  0x00000000005b1a58 in rt.dmain2._d_run_main(int, char**, extern(C) int(char[][]) function).runAll() ()
#10 0x00000000005b1946 in _d_run_main ()
#11 0x0000000000483f25 in main (argc=1, argv=0x7fffffffe838) at /home/pjotr/izip/git/opensource/D/BioD/build/__entrypoint.d:8
#12 0x00007ffff6c55b2e in __libc_start_main () from /gnu/store/l4lr0f5cjd0nbsaaf8b5dmcw1a1yypr3-glibc-2.27/lib/libc.so.6
#13 0x0000000000403e7a in _start ()
```

There appears to be an issue with the garbage collector.

**Comment by pjotrp** [comment]
We are not the only ones. https://forum.dlang.org/post/gngnwkqjdolmlpbayvmi@forum.dlang.org
